APPLICATION=drivers-application

BOARD ?= iotlab-m3 

USEMODULE += xtimer
USEMODULE += lps331ap 
USEMODULE += lsm303dlhc

DEVELHELP ?= 1

RIOTBASE ?= $(CURDIR)/../../../../RIOT

include $(RIOTBASE)/Makefile.include
